# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - release
  - nightly

notifications:
  email: false

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
    - gfortran

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("FortranFiles"); Pkg.test("FortranFiles"; coverage=true)'

after_success:
  # build and deploy documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("FortranFiles")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Coveralls and Codecov
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      julia -e 'cd(Pkg.dir("FortranFiles")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
      julia -e 'cd(Pkg.dir("FortranFiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
