name    = "FortranFiles"
uuid    = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
author  = ["Frank Otto <traktofon@gmail.com>"]
version = "0.6.0"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test   = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
